name: Build and Publish Docker Image

on:
  push:
    tags:
      - 'v*'

permissions: write-all

jobs:
  build-app:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install bun.js
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun i

      - name: Build nuxt app
        run: bun run build

      - name: Upload production bundle
        uses: actions/upload-artifact@v4
        with:
          name: production-bundle
          path: .output/

  build-docker-image:
    runs-on: ubuntu-22.04
    needs: build-app
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download production bundle
        uses: actions/download-artifact@v4
        with:
          name: production-bundle
          path: ./production-bundle

      - run: ls -l

      - run: ls -l docker

      - name: Setup Docker
        uses: docker-practice/actions-setup-docker@master

      - name: Build docker image
        run: docker build --pull --rm -f "docker/dockerfile" --tag "portfolio/portfolio:latest" .

      - name: save docker image
        run: docker save -o Portfolio.tar portfolio/portfolio:latest

      - name: Upload docker image
        uses: actions/upload-artifact@v4
        with:
          name: Portfolio.tar
          path: ./Portfolio.tar

  release:
    runs-on: ubuntu-22.04
    needs: build-docker-image
    steps:
      - name: Download docker image
        uses: actions/download-artifact@v4
        with:
          name: Portfolio.tar

      - name: Check if release exists
        id: check_release
        run: |
          if gh release view ${{ github.ref_name }}; then
            echo "exists=true" >> $GITHUB_ENV
          else
            echo "exists=false" >> $GITHUB_ENV
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub release
        if: env.exists == 'false'
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: |
            Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload docker image as release asset
        if: env.exists == 'true'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url || github.event.release.upload_url }}
          asset_path: ./Portfolio.tar
          asset_name: Portfolio.tar
          asset_content_type: application/gzip

  delete-artifacts:
    runs-on: ubuntu-22.04
    needs: release
    steps:
      - uses: geekyeggo/delete-artifact@v5
        with:
          name: |
            production-bundle
            Portfolio.tar
          failOnError: false
